<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Setup\images.zip" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Setup\images.zip">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="6.0.5" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="6.0.3" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0-beta1" />
    <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="7.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="7.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.1.0-dev-00289" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.1-dev-00896" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="5.2.3-dev-00260" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\WebBlazor.Client.csproj" />
    <ProjectReference Include="..\Shared\WebBlazor.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\images\" />
  </ItemGroup>

</Project>
